export interface Product {
  id: string;
  name: string;
  description: string;
  price: number;
  originalPrice?: number;
  category: string;
  image: string;
  rating: number;
  reviewCount: number;
  inStock: boolean;
  tags: string[];
}

export const products: Product[] = [
  {
    id: 'prod-001',
    name: 'Premium Wireless Headphones',
    description: 'High-quality noise-canceling wireless headphones with 30-hour battery life and premium sound quality.',
    price: 149.99,
    originalPrice: 199.99,
    category: 'Electronics',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=400&fit=crop',
    rating: 4.8,
    reviewCount: 1245,
    inStock: true,
    tags: ['bestseller', 'deal', 'trending'],
  },
  {
    id: 'prod-002',
    name: 'Smart Fitness Watch',
    description: 'Advanced fitness tracking with heart rate monitor, GPS, and 7-day battery life.',
    price: 199.99,
    category: 'Electronics',
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=400&fit=crop',
    rating: 4.6,
    reviewCount: 892,
    inStock: true,
    tags: ['new', 'trending'],
  },
  {
    id: 'prod-003',
    name: 'Organic Coffee Beans',
    description: 'Premium single-origin Arabica coffee beans, freshly roasted for the perfect cup.',
    price: 24.99,
    originalPrice: 29.99,
    category: 'Food & Beverage',
    image: 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=400&h=400&fit=crop',
    rating: 4.9,
    reviewCount: 2156,
    inStock: true,
    tags: ['bestseller', 'deal', 'organic'],
  },
  {
    id: 'prod-004',
    name: 'Minimalist Leather Wallet',
    description: 'Slim RFID-blocking wallet made from genuine full-grain leather.',
    price: 49.99,
    category: 'Fashion',
    image: 'https://images.unsplash.com/photo-1627123424574-724758594e93?w=400&h=400&fit=crop',
    rating: 4.7,
    reviewCount: 567,
    inStock: true,
    tags: ['trending'],
  },
  {
    id: 'prod-005',
    name: 'Eco-Friendly Water Bottle',
    description: 'Insulated stainless steel water bottle that keeps drinks cold for 24 hours.',
    price: 34.99,
    originalPrice: 44.99,
    category: 'Home & Garden',
    image: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=400&h=400&fit=crop',
    rating: 4.5,
    reviewCount: 789,
    inStock: true,
    tags: ['eco', 'deal'],
  },
  {
    id: 'prod-006',
    name: 'Mechanical Gaming Keyboard',
    description: 'RGB backlit mechanical keyboard with customizable switches and macro keys.',
    price: 129.99,
    category: 'Electronics',
    image: 'https://images.unsplash.com/photo-1541140532154-b024d705b90a?w=400&h=400&fit=crop',
    rating: 4.8,
    reviewCount: 1567,
    inStock: true,
    tags: ['bestseller', 'gaming'],
  },
  {
    id: 'prod-007',
    name: 'Yoga Mat Premium',
    description: 'Extra thick eco-friendly yoga mat with alignment lines and carrying strap.',
    price: 59.99,
    originalPrice: 79.99,
    category: 'Sports',
    image: 'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=400&h=400&fit=crop',
    rating: 4.6,
    reviewCount: 445,
    inStock: true,
    tags: ['deal', 'eco'],
  },
  {
    id: 'prod-008',
    name: 'Scented Candle Set',
    description: 'Set of 3 hand-poured soy candles with natural essential oils.',
    price: 39.99,
    category: 'Home & Garden',
    image: 'https://images.unsplash.com/photo-1602028915047-37269d1a73f7?w=400&h=400&fit=crop',
    rating: 4.4,
    reviewCount: 334,
    inStock: true,
    tags: ['new', 'gift'],
  },
  {
    id: 'prod-009',
    name: 'Wireless Charging Pad',
    description: 'Fast wireless charging pad compatible with all Qi-enabled devices.',
    price: 29.99,
    originalPrice: 39.99,
    category: 'Electronics',
    image: 'https://images.unsplash.com/photo-1586816879360-004f5b0c51e3?w=400&h=400&fit=crop',
    rating: 4.3,
    reviewCount: 678,
    inStock: true,
    tags: ['deal', 'trending'],
  },
  {
    id: 'prod-010',
    name: 'Artisan Notebook Set',
    description: 'Handcrafted leather-bound notebooks with premium paper. Set of 3.',
    price: 44.99,
    category: 'Stationery',
    image: 'https://images.unsplash.com/photo-1544816155-12df9643f363?w=400&h=400&fit=crop',
    rating: 4.9,
    reviewCount: 267,
    inStock: true,
    tags: ['bestseller', 'gift'],
  },
  {
    id: 'prod-011',
    name: 'Smart Home Speaker',
    description: 'Voice-controlled smart speaker with premium audio quality and smart home integration.',
    price: 89.99,
    originalPrice: 119.99,
    category: 'Electronics',
    image: 'https://images.unsplash.com/photo-1543512214-318c7553f230?w=400&h=400&fit=crop',
    rating: 4.5,
    reviewCount: 1123,
    inStock: true,
    tags: ['deal', 'trending', 'smart'],
  },
  {
    id: 'prod-012',
    name: 'Vintage Sunglasses',
    description: 'Classic retro-style sunglasses with UV400 protection and polarized lenses.',
    price: 79.99,
    category: 'Fashion',
    image: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=400&h=400&fit=crop',
    rating: 4.7,
    reviewCount: 456,
    inStock: true,
    tags: ['trending', 'summer'],
  },
];

export const categories = [
  'All',
  'Electronics',
  'Fashion',
  'Food & Beverage',
  'Home & Garden',
  'Sports',
  'Stationery',
];

export const reviews = [
  {
    productId: 'prod-001',
    userName: 'AudioPhile2024',
    rating: 5,
    comment: 'Best headphones I\'ve ever owned! The noise cancellation is incredible.',
    date: '2024-01-15',
  },
  {
    productId: 'prod-001',
    userName: 'MusicLover',
    rating: 4,
    comment: 'Great sound quality, but wish the ear cups were slightly larger.',
    date: '2024-01-10',
  },
  {
    productId: 'prod-002',
    userName: 'FitnessGuru',
    rating: 5,
    comment: 'Accurate tracking and the battery life is amazing!',
    date: '2024-01-12',
  },
  {
    productId: 'prod-003',
    userName: 'CoffeeAddict',
    rating: 5,
    comment: 'The best coffee I\'ve ever tasted at home. Fresh and aromatic!',
    date: '2024-01-18',
  },
];
